version: "2"
services:
    wordgenerator:
      build: ./
      container_name: word-generator
      image: word-generator:latest
      ports:
        - 5000:5000
      volumes:
        - ./logs:/var/log
        - ./data:/data

